function createfigure(XData1,YData1,XData2,YData2,XData3,YData3,XData4,YData4,XData5,YData5,XData6,YData6,title)
%CREATEFIGURE(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata

% Create figure
figure1 = figure('Tag','MLearnAppExportedScatterPlot','Name','Scatter Plot');

% Create axes
axes1 = axes('Tag','MLearnAppExportedScatterPlotAxes','Parent',figure1);

% Create line
line(XData1,YData1,'DisplayName','Spondylolisthesis - Correct',...
    'Tag','MLearnAppScatterDataCorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',18,...
    'Marker','.',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0.929 0.694 0.125]);

% Create line
line(XData2,YData2,'DisplayName','Spondylolisthesis - Incorrect',...
    'Tag','MLearnAppScatterDataIncorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',7.8,...
    'Marker','x',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0.929 0.694 0.125]);

% Create line
line(XData3,YData3,'DisplayName','Normal - Correct',...
    'Tag','MLearnAppScatterDataCorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',18,...
    'Marker','.',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0.85 0.325 0.098]);

% Create line
line(XData4,YData4,'DisplayName','Normal - Incorrect',...
    'Tag','MLearnAppScatterDataIncorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',7.8,...
    'Marker','x',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0.85 0.325 0.098]);

% Create line
line(XData5,YData5,'DisplayName','Hernia - Correct',...
    'Tag','MLearnAppScatterDataCorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',18,...
    'Marker','.',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0 0.447 0.741]);

% Create line
line(XData6,YData6,'DisplayName','Hernia - Incorrect',...
    'Tag','MLearnAppScatterDataIncorrectPrediction',...
    'Parent',axes1,...
    'MarkerSize',7.8,...
    'Marker','x',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Var2','Interpreter','none');

% Create xlabel
xlabel('Var1','Interpreter','none');

% Create title
title(strcat('Predictions:', title),'Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[19.3371388846259 83.71806119495]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-3.50579845914709 31.2576068888483]);
grid(axes1,'on');

% Set the remaining axes properties
set(axes1,'OuterPosition',[0 0 0.808924831836014 1],'TickLabelInterpreter','none');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeastoutside');
title(legend1,'Model predictions');

